# This file is part of the TUM Overleaf template.
# It is used to point the LaTeX Compiler to the class and package files
# located in the tum/ subdirectory.

ensure_path( 'TEXINPUTS', './tum//' );

$out_dir = 'target';
$bibtex = "bibtex -include-directory=.. %O %B";
